### ISSUE TITLE
shinydashboard

### ISSUE THREAD

**Issue by AltayYuzeir** [oobianom/shinyStorePlus#1]
Dear Dr. Obianom, 

This package has been amazing! I think it is a tool many Shiny users have been looking for. Thank you!
I have encountered a small issue, when I tried implementing shinyStorePlus into a shinydashboard layout. The automatic saving of input data does not seem to work. I will attach a reproducible sample. Thank you very much!

library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(shinytitle)
library(shinyStorePlus)
library(shinyjs)

ui = dashboardPage(
  skin = "purple",
  header = dashboardHeader(
    ###### Logo -------
    title = "Test"
   
  ),
  sidebar = dashboardSidebar(
    
    sidebarMenu(
      br(),
      
      menuItem(
        text = "Test",
        tabName = "test1",
        icon = icon("feather")
      )

    ),
    hr(style = "border-top: 1px solid #ffffff;")
    
  ),
  
  body = dashboardBody(
    initStore(),
    tabItems(
      tabItem(tabName = "test1", uiOutput("test1page"))
      
    ))
  
)

server = function(input, output, session){
  
  output$test1page <- renderUI({
    tabsetPanel(
      #### Player 1 upper ----
      tabPanel(tags$b(tags$span(style = "color: purple", "new")),
               
               fluidRow(
                 
                 column(
                   width = 1,
                   textInput("field1", label = NULL, width = "100%")
                 ),
                 column(
                   width = 1,
                   textInput("field2", label = NULL, width = "100%")
                 ),
                 column(
                   width = 1,
                   textInput("field3", label = NULL, width = "100%")
                 ),
                 column(
                   width = 1,
                   textInput("field4", label = NULL, width = "100%")
                 ),
                 column(
                   width = 1,
                   textInput("field5", label = NULL, width = "100%")
                 ),
                 column(
                   width = 1,
                   textInput("field6", label = NULL, width = "100%")
                 )
                 
               )
      ))
  })
  
  setupStorage(
    appId = "test",
    inputs = TRUE
  )
}

shinyApp(ui, server)

**Comment by oobianom** [comment]
Thanks.

You are having the issue because you are setting the UI using the "output" in sever. This version (0.6) only tracks the inputs, no outputs.  I am currently working on a new version that will be tracking more such as outputs and specific variables. 

In the meantime, I have moved around back to the UI as inputs and it works. Look at the code below...

library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(shinytitle)
library(shinyStorePlus)
library(shinyjs)

ui <- dashboardPage(
  skin = "purple",
  header = dashboardHeader(
    ###### Logo -------
    title = "Test"
  ),
  sidebar = dashboardSidebar(
    sidebarMenu(
      br(),
      menuItem(
        text = "Test",
        tabName = "test1",
        icon = icon("feather")
      )
    ),
    hr(style = "border-top: 1px solid #ffffff;")
  ),
  body = dashboardBody(
    initStore(),
    tabItems(
      tabItem(
        tabName = "test1",
        tabsetPanel(
          #### Player 1 upper ----
          tabPanel(
            tags$b(tags$span(style = "color: purple", "new")),
            fluidRow(
              column(
                width = 1,
                textInput("field1", label = NULL, width = "100%")
              ),
              column(
                width = 1,
                textInput("field2", label = NULL, width = "100%")
              ),
              column(
                width = 1,
                textInput("field3", label = NULL, width = "100%")
              ),
              column(
                width = 1,
                textInput("field4", label = NULL, width = "100%")
              ),
              column(
                width = 1,
                textInput("field5", label = NULL, width = "100%")
              ),
              column(
                width = 1,
                textInput("field6", label = NULL, width = "100%")
              )
            )
          )
        )
      )
    ),
    uiOutput("test1page")
  )
)

server <- function(input, output, session) {
  output$test1page <- renderUI({

  })

  setupStorage(
    appId = "test",
    inputs = TRUE
  )
}

shinyApp(ui, server)

**Comment by AltayYuzeir** [comment]
I see now. Many thanks!
