### ISSUE TITLE
shinyStorePlus does not work with shinydashboard

### ISSUE THREAD

**Issue by thiklop** [oobianom/shinyStorePlus#5]
Hi,

I'm trying to use shinyStorePlus with shinydashboard and I can't find where to write the initStore() function (there is no fluidpage function called).
If I try to write in the first lines :
dashboardPage(
    # initialize shinyStorePlus#stores
    initStore(),
...
It produces a shiny.tag error.

If I try lower : 
dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    sidebarMenu(
     # initialize shinyStorePlus#stores
     initStore(),
It doesn't initiate -> "Error in session$sendCustomMessage("retriever", result) : "

Do you have any idea ?

Regards

**Comment by oobianom** [comment]
I will look into it this weekend and get back to you.

**Comment by oobianom** [comment]
I have a resolution for you. Please try out the code below.

library(shiny)
library(shinydashboard)
library(shinyStorePlus)

ui <- dashboardPage(
  dashboardHeader(
    title = "Basic dashboard",
    initStore()
  ),
  dashboardSidebar(),
  dashboardBody(
    #Boxes need to be put in a row (or column)
    fluidRow(
      box(plotOutput("plot1", height = 250)),
      box(
        title = "Controls",
        sliderInput("slider", "Number of observations:", 1, 100, 50)
      )
    )
  )
)

server <- function(input, output, session) {
  set.seed(122)
  histdata <- rnorm(500)

  output$plot1 <- renderPlot({
    data <- histdata[seq_len(input$slider)]
    hist(data)
  })

  #IMPORTANT: Include at the bottom. Make sure to have input, output, session in sever argument
  appid <- "appltut12"
  setupStorage(appId = appid, inputs = TRUE)
}

shinyApp(ui, server)

**Comment by thiklop** [comment]
Thanks a lot, I'll try it as soon as possible and I'll let you know.

Le sam. 4 févr. 2023, 08:21, Obi Obianom ***@***.***> a
écrit :

**Comment by thiklop** [comment]
Hi,

I'm sorry but that doesn't work. 
I copied/pasted your code and I tried with R 3.6.2, 4.0.4 and 4.2.1. It always produces the same error message :
```
> runApp('temp')
List of 10
 $ name      : chr "shinyStorePlus"
 $ version   : chr "0.6"
 $ src       :List of 1
  ..$ file: chr "/.../R/library/4.2.1/shinyStorePlus/scripts"
 $ meta      : NULL
 $ script    : chr [1:2] "dexie.js" "shinystoreplus.js"
 $ stylesheet: NULL
 $ head      : NULL
 $ attachment: NULL
 $ package   : NULL
 $ all_files : logi FALSE
 - attr(*, "class")= chr "html_dependency"
Erreur dans FUN(X[[i]], ...) : Expected an object with class 'shiny.tag'.
```

**Comment by oobianom** [comment]
Ok. I find that it works if you put it within the body like below

library(shiny)
library(shinydashboard)
library(shinyStorePlus)

ui <- dashboardPage(
dashboardHeader(
title = "Basic dashboard"
),
dashboardSidebar(),
dashboardBody(
initStore(),
#Boxes need to be put in a row (or column)
fluidRow(
box(plotOutput("plot1", height = 250)),
box(
title = "Controls",
sliderInput("slider", "Number of observations:", 1, 100, 50)
)
)
)
)

server <- function(input, output, session) {
set.seed(122)
histdata <- rnorm(500)

output$plot1 <- renderPlot({
data <- histdata[seq_len(input$slider)]
hist(data)
})

#IMPORTANT: Include at the bottom. Make sure to have input, output, session in sever argument
appid <- "appltut12"
setupStorage(appId = appid, inputs = TRUE)
}

shinyApp(ui, server)

**Comment by thiklop** [comment]
It works, thanks a lot !
There were in fact two problems :
1. Where to place initStore() in the dashboardPage()
2. RTFM - beside it was written, I didn't wrote the "session" in server function argument.

Thanks again !

**Comment by oobianom** [comment]
Glad it worked for you.
